# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/Mi8937/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/Mi8937

PRODUCT_COPY_FILES += \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/prada/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/prada/MTP_Bluetooth_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/ulysse/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ulysse/MTP_Bluetooth_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/prada/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/prada/MTP_General_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/ulysse/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ulysse/MTP_General_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/prada/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/prada/MTP_Global_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/ulysse/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ulysse/MTP_Global_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/prada/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/prada/MTP_Handset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/ulysse/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ulysse/MTP_Handset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/prada/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/prada/MTP_Hdmi_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/ulysse/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ulysse/MTP_Hdmi_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/prada/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/prada/MTP_Headset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/ulysse/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ulysse/MTP_Headset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/prada/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/prada/MTP_Speaker_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/ulysse/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ulysse/MTP_Speaker_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/land/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/land/QRD_Bluetooth_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/land/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/land/QRD_General_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/land/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/land/QRD_Global_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/land/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/land/QRD_Handset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/land/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/land/QRD_Hdmi_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/land/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/land/QRD_Headset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/land/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/land/QRD_Speaker_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/santoni/QRD_SKU7_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/santoni/QRD_SKU7_Bluetooth_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/santoni/QRD_SKU7_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/santoni/QRD_SKU7_General_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/santoni/QRD_SKU7_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/santoni/QRD_SKU7_Global_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/santoni/QRD_SKU7_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/santoni/QRD_SKU7_Handset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/santoni/QRD_SKU7_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/santoni/QRD_SKU7_Hdmi_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/santoni/QRD_SKU7_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/santoni/QRD_SKU7_Headset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/santoni/QRD_SKU7_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/santoni/QRD_SKU7_Speaker_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_hx8394F_HD720p_video_BOE.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_hx8394F_HD720p_video_BOE.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_hx8394F_HD720p_video_BOE_c3a.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_hx8394F_HD720p_video_BOE_c3a.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_hx8394F_HD720p_video_BOE_c3b.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_hx8394F_HD720p_video_BOE_c3b.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_ili9881c_HD720p_video_Ebbg.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ili9881c_HD720p_video_Ebbg.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_ili9881c_HD720p_video_EbbgDJN.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ili9881c_HD720p_video_EbbgDJN.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_ili9881c_HD720p_video_Ebbg_c3a.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ili9881c_HD720p_video_Ebbg_c3a.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_ili9881c_HD720p_video_Ebbg_c3b.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ili9881c_HD720p_video_Ebbg_c3b.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_ili9881c_HD720p_video_Tianma.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_ili9881c_HD720p_video_Tianma.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_nt35521s_HD720p_video_EBBG.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35521s_HD720p_video_EBBG.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/qdcm_calib_data_nt35521s_HD720p_video_EBBG_c3a.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35521s_HD720p_video_EBBG_c3a.xml \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib/libDiracAPI_SHARED.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDiracAPI_SHARED.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib/soundfx/libdirac.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libdirac.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/hw/consumerir.led.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/consumerir.led.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/hw/consumerir.lirc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/consumerir.lirc.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/hw/consumerir.spidev.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/consumerir.spidev.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/hw/fingerprint.msm8937.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.msm8937.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/lib_fpc_tac_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib_fpc_tac_shared.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/libgf_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_algo.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/libgf_ca.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_ca.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/libgf_hal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_hal.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/bin/hvdcp_opti:$(TARGET_COPY_OUT_VENDOR)/bin/hvdcp_opti \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/rova/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/rova/QRD_Bluetooth_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/rova/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/rova/QRD_General_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/rova/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/rova/QRD_Global_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/rova/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/rova/QRD_Handset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/rova/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/rova/QRD_Hdmi_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/rova/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/rova/QRD_Headset_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/rova/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/rova/QRD_Speaker_cal.acdb \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/acdbdata/rova/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/rova/QRD_workspaceFile.qwsp \
    vendor/xiaomi/Mi8937/proprietary/vendor/etc/diracmobile.config:$(TARGET_COPY_OUT_VENDOR)/etc/diracmobile.config \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib/rfsa/adsp/dirac_resource.dar:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/dirac_resource.dar \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib/rfsa/adsp/libdirac-capiv2.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libdirac-capiv2.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/hw/gatekeeper.msm8937.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.msm8937.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/hw/gf_fingerprint.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gf_fingerprint.default.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/hw/keystore.msm8937.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.msm8937.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/libsensor_reg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsensor_reg.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/libvendor.goodix.hardware.fingerprint@1.0-service.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvendor.goodix.hardware.fingerprint@1.0-service.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/libvendor.goodix.hardware.fingerprint@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvendor.goodix.hardware.fingerprint@1.0.so \
    vendor/xiaomi/Mi8937/proprietary/vendor/lib64/sensors.ssc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/sensors.ssc.so
